# This is a basic workflow to help you get started with Actions

name: MSYS2 CI

on: [push, pull_request, workflow_dispatch]
concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, toolchain: mingw-w64-x86_64-toolchain, can-fail: true },
          { msystem: MINGW32, toolchain: mingw-w64-i686-toolchain, can-fail: true },
          { msystem: UCRT64, toolchain: mingw-w64-ucrt-x86_64-toolchain, can-fail: true },
          { msystem: CLANG64, toolchain: mingw-w64-clang-x86_64-toolchain, can-fail: true },
          { msystem: CLANG32, toolchain: '', can-fail: true }
        ]
    name: ${{ matrix.msystem }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: git msys2-devel base-devel binutils pactoys-git python-pip python-future ${{ matrix.toolchain }}
          update: true
          
      - shell: msys2 {0}
        run: |
          uname -a
          
      - name: CI-Build
        shell: msys2 {0}
        continue-on-error: ${{ matrix.can-fail }}
        id: build
        run: |
          ./waf configure
          ./waf copter
